name: Using Booleans in GitHub Actions

on:
  workflow_dispatch:

jobs:
  evaluate-boolean:
    runs-on: ubuntu-latest

    steps:
    - name: Evaluate and print based on boolean value
      run: |
        echo " ${{ false && 'a' }}"
        echo " ${{ false && 'a' || 'b' }}"
        echo " ${{ true && 'a' }}"
        echo " ${{ true && 'a' || 'b' }}"
